---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-a-app
  namespace: team-a
spec:
  template:
    spec:
      containers:
      - name: team-a-app
        image: gcr.io/google-samples/hello-app:2.0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-a-ingress
  namespace: team-a
spec:
  rules:
    - host: team-a.staging.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: team-a-svc
                port:
                  number: 8080
